
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.JTableHeader;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ELI
 */
public class Calculo_dietetico_adulto1 extends javax.swing.JFrame {

    /**
     * Creates new form Calculo_dietetico_adulto
     */
    private double GEB;
    private double ETA;
    private double AF;
    private double GET;
    
    public Calculo_dietetico_adulto1() {
        initComponents();
        setLocationRelativeTo(null);
        
        JTableHeader jtableHeader = jTable1.getTableHeader();
        jtableHeader.setDefaultRenderer(new GestionEncabezadoTabla());
        jTable1.setTableHeader(jtableHeader);
        
        btnLimpiar.setOpaque(false);
        btnLimpiar.setContentAreaFilled(false);
        btnLimpiar.setBorderPainted(false);
        
        btnCalculos.setOpaque(false);
        btnCalculos.setContentAreaFilled(false);
        btnCalculos.setBorderPainted(false);
        
        btnRegresar.setOpaque(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtETA = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtGEB = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtGET = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        btnCalculos = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnSiguiente = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo3.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(923, 37, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/texto_calculo_d.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 37, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 35)); // NOI18N
        jLabel5.setText("GEB:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        txtETA.setBackground(new java.awt.Color(204, 204, 255));
        txtETA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtETA, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 120, 43));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 35)); // NOI18N
        jLabel6.setText("ETA:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        txtGEB.setBackground(new java.awt.Color(204, 204, 255));
        txtGEB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtGEB, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 120, 43));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 35)); // NOI18N
        jLabel7.setText("AF:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        txtAF.setBackground(new java.awt.Color(204, 204, 255));
        txtAF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtAF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 120, 43));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 35)); // NOI18N
        jLabel8.setText("GET:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, -1));

        txtGET.setBackground(new java.awt.Color(204, 204, 255));
        txtGET.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtGET, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 120, 43));

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/Regresar.png"))); // NOI18N
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, 201, -1));

        btnCalculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/Calcular.png"))); // NOI18N
        btnCalculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculosActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 570, 199, -1));

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/Limpiar.png"))); // NOI18N
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 570, 199, -1));

        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"MC", null, null, null},
                {"Proteinas", null, null, null},
                {"Lípidos", null, null, null},
                {"Total", null, null, null}
            },
            new String [] {
                "", "%", "gr", "Kcal"
            }
        ));
        jTable1.setRowHeight(50);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 670, 240));

        btnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/Siguiente.png"))); // NOI18N
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 570, 200, 70));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/blanco.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtGEB.setText("");
        txtETA.setText("");
        txtGET.setText("");
        txtAF.setText("");
        
        String [][] a=new String[jTable1.getRowCount()][jTable1.getColumnCount()];
        a[0][0]="MC";
        a[1][0]="Proteinas";
        a[2][0]="Lípidos";
        a[3][0]="Total";
        for(int i=0;i<jTable1.getRowCount();i++){
            for(int j=1;j<jTable1.getColumnCount();j++){
                a[i][j]="";
            }
        }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                a,new String []{
                    "","%","gr","Kcal"
                }
        ));
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        Calculo_dietetico_adulto v1=new Calculo_dietetico_adulto();
        v1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnCalculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculosActionPerformed
        
        try{
            Connection con=null;
            con = BD.getConection();
                
            PreparedStatement ps;
            ResultSet res;
            
            ps=con.prepareStatement("CALL Consultar_calculo1("+Datos_Generales.getid()+")");
            res=ps.executeQuery();
            res.next();
            
            //calcular valores
            if(Datos_Generales.getsexo().equalsIgnoreCase("Hombre")){
                GEB=66+(13.7*res.getDouble("peso"))+(5*res.getDouble("talla"))-(6.8*Datos_Generales.getedad());                
            }else if(Datos_Generales.getsexo().equalsIgnoreCase("Mujer")){
                GEB=655+(9.6*res.getDouble("peso"))+(1.8*res.getDouble("talla"))-(4.7*Datos_Generales.getedad());
            }
            if(res.getString("act_fisica").equalsIgnoreCase("Sedentario")){
                AF=30*GEB;
            }else if(res.getString("act_fisica").equalsIgnoreCase("Moderada")){
                AF=50*GEB;
            }else{
                AF=100*GEB;
            }
            ETA=GEB*.1;
            GET= ETA+AF;
            //poner etiquetas
            txtGEB.setText(""+GEB);
            txtETA.setText(""+ETA);
            txtAF.setText(""+AF);
            txtGET.setText(""+GET);
            //rellenar tabla
            
            double gr1=2*res.getDouble("peso");
            double kcal1=gr1*4;
            double por1= kcal1*100/GET; 
            jTable1.setValueAt(String.format("%5.2f",gr1),1,2);
            jTable1.setValueAt(String.format("%5.2f",kcal1),1,3);
            jTable1.setValueAt(String.format("%5.2f",por1),1,1);
            
            double por2=55;
            double kcal2=55*GET/100;
            double gr2=kcal2/4;
            jTable1.setValueAt(String.format("%5.2f",gr2),0,2);
            jTable1.setValueAt(String.format("%5.2f",kcal2),0,3);
            jTable1.setValueAt(String.format("%5.2f",por2),0,1);;
            
            double por3=100-por1-por2;
            double kcal3=por3*GET/100;
            double gr3=kcal3/9;
            jTable1.setValueAt(String.format("%5.2f",gr3),2,2);
            jTable1.setValueAt(String.format("%5.2f",kcal3),2,3);
            jTable1.setValueAt(String.format("%5.2f",por3),2,1);
            
            double port=por1+por2+por3;
            double kcalt=kcal1+kcal2+kcal3;
            double grt=gr1+gr2+gr3;
            jTable1.setValueAt(String.format("%5.2f",grt),3,2);
            jTable1.setValueAt(String.format("%5.2f",kcalt),3,3);
            jTable1.setValueAt(String.format("%5.2f",port),3,1);
            //guardar valores en la bd
            ps=con.prepareStatement("CALL Actualizar_calculo("+Datos_Generales.getid()+","+GEB+","+ETA+","+AF+","+GET+")");
            res=ps.executeQuery();
        }catch(Exception e){
            System.out.print(e);
        }
    }//GEN-LAST:event_btnCalculosActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        
    }//GEN-LAST:event_btnSiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculo_dietetico_adulto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculo_dietetico_adulto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculo_dietetico_adulto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculo_dietetico_adulto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculo_dietetico_adulto1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculos;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAF;
    private javax.swing.JTextField txtETA;
    private javax.swing.JTextField txtGEB;
    private javax.swing.JTextField txtGET;
    // End of variables declaration//GEN-END:variables
}
