
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ELI
 */
public class Datos_Generales extends javax.swing.JFrame {
    
    private boolean guardado;
    /**
     * Creates new form Datos_Generales
     */
    public Datos_Generales() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        guardado=false;
        
        btnRegresar.setOpaque(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setBorderPainted(false);
        
        btnGuardar.setOpaque(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setBorderPainted(false);
        
        btnSiguiente.setOpaque(false);
        btnSiguiente.setContentAreaFilled(false);
        btnSiguiente.setBorderPainted(false);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtOcupacion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCel = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDomicilio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtSexo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtEC = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtMotivo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtTelCasa = new javax.swing.JTextField();
        btnSiguiente = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 30, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 150, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/texto_Historial_Clinico.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/text_Datos_Generales.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Ocupación:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 300, -1, 30));

        txtOcupacion.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(txtOcupacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 300, 220, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Nombre: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, 30));

        txtNombre.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 810, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Cel:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 350, -1, 30));

        txtCel.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(txtCel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 350, 140, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Edad:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, -1, 30));

        txtEdad.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 100, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Estado Civil:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, -1, 30));

        txtDomicilio.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(txtDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 170, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Sexo:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, 30));

        txtSexo.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(txtSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 100, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Motivo de la consulta");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, -1, 30));

        txtEC.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(txtEC, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 130, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Domicilio:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, -1, 30));

        txtMotivo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(txtMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 870, 150));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Tel. Casa:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, 30));

        txtTelCasa.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(txtTelCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 140, 30));

        btnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/Siguiente.png"))); // NOI18N
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 590, 210, -1));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/Guardar.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 590, 210, -1));

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/Regresar.png"))); // NOI18N
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 590, 200, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/blanco.png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        Menu v1=new Menu();
        v1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(txtNombre.getText().equalsIgnoreCase("") || txtSexo.getText().equalsIgnoreCase("") || txtEdad.getText().equalsIgnoreCase("") || txtEC.getText().equalsIgnoreCase("") || txtOcupacion.getText().equalsIgnoreCase("") || txtTelCasa.getText().equalsIgnoreCase("") || txtDomicilio.getText().equalsIgnoreCase("") || txtCel.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null,"un campo esta vacio, favor de rellenar");
        }else{
            guardado=true;
            setedad(Integer.parseInt(txtEdad.getText()));
            setnombre(txtNombre.getText());
            setsexo(txtSexo.getText());
            
            try{
                Connection con=null;
                con = BD.getConection();
                
                PreparedStatement ps;
                ResultSet res;
                
                ps=con.prepareStatement("CALL Insertar_Paciente('"+txtNombre.getText()+"','"+txtSexo.getText()+"',"+Integer.parseInt(txtEdad.getText())+",'"+txtEC.getText()+"','"+txtOcupacion.getText()+"','"+txtTelCasa.getText()+"','"+txtDomicilio.getText()+"','"+txtCel.getText()+"','"+txtMotivo.getText()+"')");
                res=ps.executeQuery();
                
                ps=con.prepareStatement("CALL retorno_id('"+getnombre()+"',"+getedad()+")");
                res=ps.executeQuery();
                res.next();
                setid(res.getInt("idPaciente"));
                
                if(edad<18){
                    ps=con.prepareStatement("CALL insertar_infante("+getid()+")");
                    res=ps.executeQuery();
                }
                
            }catch(Exception e){
                System.out.print(e);
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        if (guardado==true){
            if(Integer.parseInt(txtEdad.getText())>=18){
                Agregar_Paciente_Adulto v1=new Agregar_Paciente_Adulto();
                v1.setVisible(true);
                this.setVisible(false);
            } else {
                Agregar_Paciente_Infante v1=new Agregar_Paciente_Infante();
                v1.setVisible(true);
                this.setVisible(false);
            }
        }else{
            JOptionPane.showMessageDialog(null,"No ha guardado");
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed
    
    private static int edad;
    private static String nombre;
    private static int id;
    private static String sexo;
    
    public static void setedad(int e){
        edad=e;
    }
    public static int getedad(){
        return edad;
    }
    public static void setnombre(String s){
        nombre=s;
    }
    public static String getnombre(){
        return nombre;
    }
    public static void setid(int i){
        id=i;
    }
    public static int getid(){
        return id;
    }
    public static void setsexo(String s){
        sexo=s;
    }
    public static String getsexo(){
        return sexo;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Datos_Generales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Datos_Generales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Datos_Generales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Datos_Generales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Datos_Generales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCel;
    private javax.swing.JTextField txtDomicilio;
    private javax.swing.JTextField txtEC;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtMotivo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtOcupacion;
    private javax.swing.JTextField txtSexo;
    private javax.swing.JTextField txtTelCasa;
    // End of variables declaration//GEN-END:variables
}
