
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.table.JTableHeader;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ELI
 */
public class Registro24h extends javax.swing.JFrame {
    
    static int []recuadro=new int[2];
    static int carbo=0;
    static int proteinas=0;
    static int lipidos=0;
    java.util.Date fecha = new Date();
    /**
     * Creates new form Registro24h
     */
    public Registro24h() {
        initComponents();
        
        setLocationRelativeTo(null);
         
        jTable1.setValueAt("Desayuno", 0, 0);
        jTable1.setValueAt("Colación", 1, 0);
        jTable1.setValueAt("Almuerzo", 2, 0);
        jTable1.setValueAt("Merienda", 3, 0);
        jTable1.setValueAt("Cena", 4, 0);
        
        JTableHeader jtableHeader = jTable1.getTableHeader();
        jtableHeader.setDefaultRenderer(new GestionEncabezadoTabla());
        jTable1.setTableHeader(jtableHeader);
        
        btnLimpiar.setOpaque(false);
        btnLimpiar.setContentAreaFilled(false);
        btnLimpiar.setBorderPainted(false);
        
        btnGuardar.setOpaque(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setBorderPainted(false);
        
        labelPaciente.setText(Datos_Generales.getnombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        labelPaciente = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtObservaciones = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Tiempo", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes"
            }
        ));
        jTable1.setRowHeight(65);
        jTable1.setSurrendersFocusOnKeystroke(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 211, 720, 364));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo3.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(964, 21, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/texto_R24H.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 36, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Total Carbohidratos:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 590, -1, -1));

        jLabel4.setBackground(new java.awt.Color(229, 242, 254));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("0");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 590, 80, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Total Proteina:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 590, -1, -1));

        jLabel6.setBackground(new java.awt.Color(229, 242, 254));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("0");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 590, 83, 20));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/Guardar3.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(951, 620, 201, -1));

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/Limpiar2.png"))); // NOI18N
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 620, 171, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel7.setText("Paciente:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        labelPaciente.setBackground(new java.awt.Color(229, 242, 254));
        labelPaciente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPaciente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(labelPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 280, 18));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Observaciones");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        txtObservaciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 280, 210));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Azul.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Total Lipidos:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 590, -1, -1));

        jLabel12.setBackground(new java.awt.Color(229, 242, 254));
        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("0");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 590, 83, 20));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/Regresar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 620, 200, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/blanco.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int x=jTable1.getSelectedColumn();
        int y=jTable1.getSelectedRow();
        if(x>0){
            setlocacion(x,y);
            Alimentos v1= new Alimentos();
            v1.setVisible(true);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtObservaciones.setText("");
        String [][] a=new String[jTable1.getRowCount()][jTable1.getColumnCount()];
        a[0][0]="Desayuno";
        a[1][0]="Colación";
        a[2][0]="Almuerzo";
        a[3][0]="Merienda";
        a[4][0]="Cena";
        for(int i=0;i<jTable1.getRowCount();i++){
            for(int j=1;j<jTable1.getColumnCount();j++){
                a[i][j]="";
            }
        }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                a,new String []{
                    "Tiempo","Lunes","Martes","Miercoles","Jueves","Viernes"
                }
        ));
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String lunes="";
        String martes="";
        String miercoles="";
        String jueves="";
        String viernes="";
        
        for (int i=0;i<5;i++){
            if(jTable1.getValueAt(i,1)!=null){
                lunes+=(String)jTable1.getValueAt(i,1);
                if(i<4){
                    lunes+="$";
                }
            }
        }
        for (int i=0;i<5;i++){
            if(jTable1.getValueAt(i,2)!=null){
                martes+=(String)jTable1.getValueAt(i,2);
                if(i<4){
                    martes+="$";
                }
            }
        }
        for (int i=0;i<5;i++){
            if(jTable1.getValueAt(i,3)!=null){
                miercoles+=(String)jTable1.getValueAt(i,3);
                if(i<4){
                    miercoles+="$";
                }
            }
        }
        for (int i=0;i<5;i++){
            if(jTable1.getValueAt(i,4)!=null){
                jueves+=(String)jTable1.getValueAt(i,4);
                if(i<4){
                    jueves+="$";
                }
            }
        }
        for (int i=0;i<5;i++){
            if(jTable1.getValueAt(i,5)!=null){
                viernes+=(String)jTable1.getValueAt(i,5);
                if(i<4){
                    viernes+="$";
                }
            }
        }
        
        try{
            Connection con=null;
            con = BD.getConection();
            
            PreparedStatement ps;
            ResultSet res;
                
            ps=con.prepareStatement("CALL Insertar_registro24h("+Datos_Generales.getid()+",'"+(fecha.getYear()+1900)+"-"+fecha.getMonth()+"-"+fecha.getDay()+"','"+lunes+"','"+martes+"','"+miercoles+"','"+jueves+"','"+viernes+"',"+carbo+","+proteinas+","+lipidos+",'"+txtObservaciones.getText()+"')");
            res=ps.executeQuery();
            
            Calculo_dietetico_adulto v1=new Calculo_dietetico_adulto();
            v1.setVisible(true);
            this.setVisible(false);
        }catch(Exception e){
            System.out.print(e);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Agregar_Paciente_Adulto v1=new Agregar_Paciente_Adulto();
        v1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public static int[] getlocacion(){
        return recuadro;
    }
    public static void setlocacion(int x, int y){
        recuadro[0]=x;
        recuadro[1]=y;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro24h.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro24h.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro24h.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro24h.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro24h().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelPaciente;
    private javax.swing.JTextField txtObservaciones;
    // End of variables declaration//GEN-END:variables
}
