
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ELI
 */
public class Tabla_Percentiles3 extends javax.swing.JFrame {
    
    private String sexo=Datos_Generales.getsexo();
    private boolean guardado;
    /**
     * Creates new form Tabla_Percentiles1
     */
    public Tabla_Percentiles3() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        guardado=false;
        
        btnRegresar.setOpaque(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setBorderPainted(false);
        
        btnGuardar.setOpaque(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setBorderPainted(false);
        
        btnSiguiente.setOpaque(false);
        btnSiguiente.setContentAreaFilled(false);
        btnSiguiente.setBorderPainted(false);
        
        if (sexo.equalsIgnoreCase("Hombre")){
            txtCoordenada1.setEditable(false);
            txtComentarios.setEditable(false);
        }else{
            txtCoordenada.setEditable(false);
            txtComentarios1.setEditable(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtComentarios = new javax.swing.JTextField();
        btnSiguiente = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtComentarios1 = new javax.swing.JTextField();
        txtCoordenada1 = new javax.swing.JTextField();
        txtCoordenada = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1050, 690));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo3.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/texto_Percentiles2_1.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("COORDENADA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, -1, -1));

        txtComentarios.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        txtComentarios.setForeground(new java.awt.Color(153, 153, 153));
        txtComentarios.setText("Comentarios:");
        txtComentarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtComentarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComentariosActionPerformed(evt);
            }
        });
        getContentPane().add(txtComentarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 610, 150));

        btnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/Siguiente.png"))); // NOI18N
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 590, 210, -1));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/Guardar3.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 590, 200, -1));

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/Regresar.png"))); // NOI18N
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 590, 210, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Talla para la edad");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 150, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TablaH2.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TablaM2.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("COORDENADA");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, -1));

        txtComentarios1.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        txtComentarios1.setForeground(new java.awt.Color(153, 153, 153));
        txtComentarios1.setText("Comentarios:");
        txtComentarios1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtComentarios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComentarios1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtComentarios1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 610, 150));

        txtCoordenada1.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(txtCoordenada1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 200, 30));

        txtCoordenada.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(txtCoordenada, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 200, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/blanco.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        Tabla_Percentiles2 v1=new Tabla_Percentiles2();
        v1.setVisible(true);
        this.setVisible(false);                          
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        guardado=true;
        try{
            Connection con=null;
            con = BD.getConection();
                
            PreparedStatement ps;
            ResultSet res;
            
            if (sexo.equalsIgnoreCase("Hombre")){
                ps=con.prepareStatement("CALL Actualizar_tabla2("+Datos_Generales.getid()+",'"+txtCoordenada.getText()+"','"+txtComentarios1.getText()+"')");
                res=ps.executeQuery();
            }else{
                ps=con.prepareStatement("CALL Actualizar_tabla2("+Datos_Generales.getid()+",'"+txtCoordenada1.getText()+"','"+txtComentarios.getText()+"')");
                res=ps.executeQuery();
            }
            
               
        }catch(Exception e){
            System.out.print(e);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        if (guardado==true){
            Tabla_Percentiles4 v1=new Tabla_Percentiles4();
            v1.setVisible(true);
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null,"No ha guardado");
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void txtComentarios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComentarios1ActionPerformed
        txtComentarios1.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtComentarios1ActionPerformed

    private void txtComentariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComentariosActionPerformed
        txtComentarios.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtComentariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tabla_Percentiles1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tabla_Percentiles1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tabla_Percentiles1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tabla_Percentiles1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tabla_Percentiles3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtComentarios;
    private javax.swing.JTextField txtComentarios1;
    private javax.swing.JTextField txtCoordenada;
    private javax.swing.JTextField txtCoordenada1;
    // End of variables declaration//GEN-END:variables
}
